### ISSUE TITLE
submit button action > /contactProcess problem

### ISSUE THREAD

**Issue by evan70** [flextype-plugins/contact#1]
Slim Application Error

The application could not run because of the following error:
Details
Type: RuntimeException
Message: Callable Flextype\Plugin\Contact\Controllers\ContactController does not exist
File: /var/www/docroot/flex/vendor/bnf/slim3-psr15/src/CallableResolver.php
Line: 85

thank you

**Comment by Awilum** [comment]
try https://github.com/flextype-plugins/contact/releases/download/v1.9.1/contact-1.9.1.zip

**Comment by evan70** [comment]
Thank Ya :)
